---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: _posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: ''
  label: Pages
  create: all
  match: "*.html"
  exclude: README.md
- type: heading
  label: Documentation
- type: document
  path: README.md
  label: README
  read_only: true
upload_dir: archive
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  - RUBY_VERSION=2.6.1
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
